### ISSUE TITLE
Presence channel whisper doesn't work

### ISSUE THREAD

**Issue by romakov** [happyDemon/vue-echo#15]
Presence channel whisper doesn't work, because this.channel.whisper is not a function.
`inputType: function () {
            this.channel
                .whisper('typing', {
                    name: this.user.name
                });
        },`

**Comment by happyDemon** [comment]
@romakov  https://github.com/laravel/echo/issues/103

**Comment by romakov** [comment]
I've tried to use the laravel-echo stanalone and it works fine
```javascript
created: function () {
    this.channel = window.Echo.join('chat')
                    .listenForWhisper('typing', (e) => {
                            console.log(e.name);
                    });
},
methods: {
    inputType: function () {
        this.channel
            .whisper('typing', {
                name: this.user.name
            });
    }
}
```
But in this pakage it doesn't work

**Comment by romakov** [comment]
I fixed the issue. My require of the socket.io-client was wrong and error didn't display. 
Bad way:
`window.io = require('socket.io-client');`
Good way:
`const io = window.io = require('socket.io-client');`

**Comment by romakov** [comment]
Sorry. My fault. I've gotten the issue again, when I've tried import by this way:
`import VueEcho from 'vue-echo';`
But when I've tried import by this way it works fine:
`import VueEcho from 'vue-echo/vue-echo'`
