### ISSUE TITLE
Cluster specifying

### ISSUE THREAD

**Issue by Asxer** [happyDemon/vue-echo#20]
I've got following error
![image.png](http://joxi.ru/J2bY7gLT4QZqem.jpg)

As you can see I cannot connect to pusher ws because cluster is not specified. I cannot find in documentation where I can set it. Could you please explain how can I do it?

**Comment by sorribes22** [comment]
Same problem, have you solvet it yet?
![seleccio_059](https://user-images.githubusercontent.com/23049412/39110876-2141cbfa-46d3-11e8-8cf9-dcce278fcff7.png)
Thanks

**Comment by happyDemon** [comment]
@Asxer @sorribes22 https://laravel.com/docs/5.6/broadcasting#receiving-broadcasts

this package initializes the same way as laravel-echo does
https://github.com/happyDemon/vue-echo#initialize

**Comment by chantz007** [comment]
The problem having solved yet. But the issue was close. Now I am also exactly face on this issue.

**Comment by happyDemon** [comment]
@chantz007 as initially said, you can define the cluster, the same way you would when you initialize laravel echo without this package. documentation is linked in my previous comment.
