### ISSUE TITLE
1.02 or 1.0.2?

### ISSUE THREAD

**Issue by irazasyed** [happyDemon/vue-echo#22]
It looks like there's some issue with the tag as the last version published on [NPM](https://www.npmjs.com/package/vue-echo) is still `1.0.1` and I'm unable to get the latest version and I think it's because of the latest tag which is `1.02` and it's unable to detect?

Can you please properly tag with correct version?

**Comment by irazasyed** [comment]
@happyDemon Can you please take a look at this issue?

**Comment by happyDemon** [comment]
@irazasyed I just published a new version to npm, sorry for the delay, work's been keeping me busy.

**Comment by irazasyed** [comment]
@happyDemon No worries. Thanks for publishing the new version. Appreciated.
